image: docker:19.03.1

before_script:
  - docker info

run_test:
  script:
  - docker run -v workflow_frogs:/workflow_frogs bgruening/planemo test --galaxy_url http://138.102.144.93/ --galaxy_user_key "5da80f57584b5c6df225a45479aae519" --no_shed_install --engine /workflow_frogs/workflow_frogs.ga