language: ruby

services:
 - docker

before_install: cd project

before_script:
 - docker pull bgruening/planemo

script:
 - docker run -v $TRAVIS_BUILD_DIR/.git/workflow_frogs:/workflow_frogs bgruening/planemo test --galaxy_url http://138.102.144.93/ --galaxy_user_key "5da80f57584b5c6df225a45479aae519" --no_shed_install --engine external_galaxy workflow_frogs/workflow_frogs.ga