language: ruby

env:
  global:
    secure: iyzavPrZQ5E9kRvtGUVjd73qNpLgLvmjd/u/LlNeUBILNqs+N2f8SPq1cTx7oy6hPV362kwoPjlFMQmZvwZ3Iph+DOGggDhF2aSM2xzCJY9wXyv48C1qTLTVBrXcMyplXClhySRP7JSCjSyCzyL7ByfDQo9WgST4MkW7RtF4ow22a3/M2VGbETbVkqasSK0WelN5GhyYdWPthjS9BTlp7KJwDmya3J2MSdNIhr3ZyvtUmx7x1lQuonQp2QJXRulrRMMlKvKqTfQfA9CwhXAzpi642nKk/fiJX6ln2gp4Stzg574I9w0wXhde78NGF5tAtRym9FaFnFDL9zbZ5AZT469Qy9YmumPc6sHSHY+gvu4JEYpA6+5GgnikX76oJ7BTmYFaV6u5rcFZxgXE1/zgEY/LY3YE8yikQblkuRBp1mVeOZgQZKWhMNT9a8GQNUGUV4XCsnczW/MIRZP51hBFbnWjXd+m8ncvoTPtRoL3WDj3IBtWJqSgOxOzroWvJcZhDJ3lWbRcvG5hUkCzF2Aypf2sCjwc9DECYLDMrMiKH+O1hzGy9IFqJRXKpKKDIp1MKRzsiepU9Ed6X7I+Jk+gSgsgz9expLWBIZa55Zee0PZsvOOKyB1HUmrLPG4dkiZPpvV7jIJCFkTjwzYZo9d72AdpVl/lf99WFw6bYY5iOgI=

services:
  - docker

before_script:
  - docker pull bgruening/planemo

script:
  - travis_wait 30 docker run -v $TRAVIS_BUILD_DIR/workflow_frogs:/workflow_frogs bgruening/planemo test --galaxy_url http://138.102.144.93/ --galaxy_user_key iyzavPrZQ5E9kRvtGUVjd73qNpLgLvmjd/u/LlNeUBILNqs+N2f8SPq1cTx7oy6hPV362kwoPjlFMQmZvwZ3Iph+DOGggDhF2aSM2xzCJY9wXyv48C1qTLTVBrXcMyplXClhySRP7JSCjSyCzyL7ByfDQo9WgST4MkW7RtF4ow22a3/M2VGbETbVkqasSK0WelN5GhyYdWPthjS9BTlp7KJwDmya3J2MSdNIhr3ZyvtUmx7x1lQuonQp2QJXRulrRMMlKvKqTfQfA9CwhXAzpi642nKk/fiJX6ln2gp4Stzg574I9w0wXhde78NGF5tAtRym9FaFnFDL9zbZ5AZT469Qy9YmumPc6sHSHY+gvu4JEYpA6+5GgnikX76oJ7BTmYFaV6u5rcFZxgXE1/zgEY/LY3YE8yikQblkuRBp1mVeOZgQZKWhMNT9a8GQNUGUV4XCsnczW/MIRZP51hBFbnWjXd+m8ncvoTPtRoL3WDj3IBtWJqSgOxOzroWvJcZhDJ3lWbRcvG5hUkCzF2Aypf2sCjwc9DECYLDMrMiKH+O1hzGy9IFqJRXKpKKDIp1MKRzsiepU9Ed6X7I+Jk+gSgsgz9expLWBIZa55Zee0PZsvOOKyB1HUmrLPG4dkiZPpvV7jIJCFkTjwzYZo9d72AdpVl/lf99WFw6bYY5iOgI= --no_shed_install --engine external_galaxy /workflow_frogs/workflow_frogs.ga
