language: ruby

env:
  global:
  - secure: FPGthXoAIQdDRk/BqPCYnexueZPrDsF9pZH5GmeerA1vEiTZbBNUHFmEatZCjc90mpaI1ULRzcnviDkd22lfhG3e9CwCIJWcHSPOP2ElDEerjAIc07YupO7jeSGVO1YTGgcX2f/5PDJVgXx7DV2lxSeZrVvMmVRui0H87tZFzF7w5G8GrGF7MmrUwukVWivp+Nl/k3TNPqQavrPsb7jeuQ2R2JiZ+FbRBHMDVEq7l+zFE7ArAX3bR6Nt25QNtObBYSSPlrnUEU2nXZkb9qqI8z3QZDgk6aWlZEExARMEUx9P1HP1lZ3LjmPWfClo4sUkNSBpnZb2Hliu9pgbnmiLLFs5DkUER6+Mo3PoJtdRPkFaNBLXvh8kja+B1P2LpnRymxOKBYrkL8YlM17jDa5TIxPIyhUVuHV0dd8yJQpHgQy2Fylfyph/69wvz9DLadPYTW34h3Bwgxwhw7NSPljQvz39mcXvF8TjrnH70eZLJ4i7AXG8ynRdZaT8tOrCcMXMgInhqIdooP8l3ZthxQ2pJO9BapIWGoy4YkoQGokvGtrhMxXmdsM9frCe2fJC474gkHeCSyP72CBXqTlZGv8OVMBwmnEQmVLinnxdPOdxQutDtAZOdg80gJLe/I8GTJYW2FSHrCXiRKrvX1x5xJNyIGRXaA/FYTFIcpvabE+H/Vc=

services:
  - docker

before_script:
  - docker pull bgruening/planemo

script:
  - travis_wait 30 docker run -v $TRAVIS_BUILD_DIR/workflow_frogs:/workflow_frogs bgruening/planemo test --galaxy_url http://migale.jouy.inra.fr/galaxy/ --galaxy_user_key $GALAXYPROD_API_KEY --no_shed_install --engine external_galaxy /workflow_frogs/workflow_frogs.ga
