language: ruby

services:
 - docker

install:
 - gem install travis

before_script:
 - travis encrypt GXYPROD_API_KEY="5da80f57584b5c6df225a45479aae519" --add
 - docker pull bgruening/planemo

script:
 - travis_wait 30 docker run -v $TRAVIS_BUILD_DIR/workflow_frogs:/workflow_frogs bgruening/planemo test --galaxy_url http://138.102.144.93/ --galaxy_user_key $GXYPROD_API_KEY --no_shed_install --engine external_galaxy /workflow_frogs/workflow_frogs.ga